// Generated by CoffeeScript 1.7.1
(function() {
  var LIVERELOAD_PORT, lrSnippet, mountFolder;

  LIVERELOAD_PORT = 35729;

  lrSnippet = require("connect-livereload")({
    port: LIVERELOAD_PORT
  });

  mountFolder = function(connect, dir) {
    return connect["static"](require("path").resolve(dir));
  };

  module.exports = function(grunt) {
    var yeomanConfig;
    require("time-grunt")(grunt);
    require("load-grunt-tasks")(grunt);
    yeomanConfig = {
      app: "",
      tmp: '.tmp'
    };
    grunt.initConfig({
      yeoman: yeomanConfig,
      watch: {
        styles: {
          files: ["<%= yeoman.app %>/styles/{,*/}*.css"],
          tasks: ["copy:styles"]
        },
        livereload: {
          files: ["<%= yeoman.app %>/*.html", "<%= yeoman.app %>/{,*/}{,*/}{,*/}*.css", "<%= yeoman.app %>/{,*/}{,*/}{,*/}*.js", "<%= yeoman.app %>/images/{,*/}*.{png,jpg,jpeg,gif,webp,svg}"]
        }
      },
      connect: {
        options: {
          port: 3001,
          hostname: "0.0.0.0"
        },
        livereload: {
          options: {
            keepalive: true,
            livereload: LIVERELOAD_PORT,
            middleware: function(connect) {
              return [mountFolder(connect, yeomanConfig.tmp), mountFolder(connect, yeomanConfig.app)];
            }
          }
        }
      },
      open: {
        server: {
          path: "http://localhost:<%= connect.options.port %>"
        }
      }
    });
    grunt.registerTask("server", ["open", "connect:livereload"]);
    return grunt.registerTask("default", ["server"]);
  };

}).call(this);
