// Generated by CoffeeScript 1.7.1
(function() {
  var Application, _defaultMetabolism;

  Application = void 0;

  _defaultMetabolism = 100;

  Application = Backbone.View.extend({
    events: {
      touchstart: "startPress",
      mousedown: "startPress",
      mouseup: "endPress",
      touchend: "endPress"
    },
    startPress: function() {
      return this.isPressing = true;
    },
    endPress: function() {
      return this.isPressing = false;
    },
    initialize: function(columns, rows, size) {
      _.bindAll(this);
      this.columns = columns;
      this.rows = rows;
      this.cellSize = size;
      this.paused = true;
      this.setElement("#GameOfLife");
      this.buildCells();
      this.render();
      $("#Start").on("click", this.toggleBtnClicked);
      $("#Clear").on("click", this.cleanSlate);
      return $("#Random").on("click", this.randomize);
    },
    buildCells: function() {
      var cell2d, curModel, curView, i, j;
      i = void 0;
      j = void 0;
      curModel = void 0;
      curView = void 0;
      cell2d = [];
      this.cells = [];
      i = 0;
      while (i < this.rows) {
        cell2d[i] = [];
        j = 0;
        while (j < this.columns) {
          curModel = new CellModel({
            x: i,
            y: j,
            size: this.cellSize
          });
          curView = new CellView({
            model: curModel,
            app: this
          });
          cell2d[i].push(curModel);
          this.cells.push(curModel);
          this.$el.append(curView.el);
          j++;
        }
        this.$el.append("<br/>");
        i++;
      }
      return _.each(this.cells, (function(cell) {
        return cell.calculateNeighbors(cell2d);
      }).bind(this));
    },
    toggleBtnClicked: function() {
      if (this.paused) {
        return this.start();
      } else {
        return this.stop();
      }
    },
    stop: function() {
      $("body").removeClass("running");
      this.paused = true;
      return $("#Start").text("Start");
    },
    start: function() {
      $("body").addClass("running");
      this.paused = false;
      this.metabolism = $("#Metabolism").val() || _defaultMetabolism;
      this.live();
      return $("#Start").text("Stop");
    },
    live: function() {
      _.each(this.cells, function(cell) {
        return cell.compete();
      });
      _.each(this.cells, function(cell) {
        return cell.step();
      });
      if (!this.paused) {
        return setTimeout(this.live, this.metabolism);
      }
    },
    cleanSlate: function() {
      _.each(this.cells, function(cell) {
        return cell.kill();
      });
      _.each(this.cells, function(cell) {
        return cell.step();
      });
      return this.stop();
    },
    randomize: function() {
      return _.each(this.cells, function(cell) {
        return cell.randomize();
      });
    }
  });

  window.Application = Application;

}).call(this);
